name: Generate GitHub Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake (dark)
        uses: Platane/snk@v3
        with:
          github_user_name: xProv25
          outputs: |
            dist/github-snake-dark.svg?color_snake=#f472b6&color_dots=#1d0f1c,#361531,#4e163f,#6c1b4e,#b0427e
      - name: Generate snake (light)
        uses: Platane/snk@v3
        with:
          github_user_name: xProv25
          outputs: |
            dist/github-snake-light.svg?color_snake=#d63384&color_dots=#fdf0f6,#fbd7e9,#f7b7d6,#f28cc0,#e75aa5

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/*.svg
          git commit -m "chore: regenerate contribution snake" || echo "No changes to commit"
          git push